Feature/configurable accent color
DiverOfDark/KNOMI pull request #54
Opened 2023-10-30 18:51 UTC by jMaddrell

2023-10-30 18:52 UTC, jMaddrell commented on Firmware/src/network/KnomiWebServer.cpp
> +      ESP.restart();
Without invalidating objects this was the easiest way to apply the changes, happy to look at invalidating objects instead if you'd prefer?

2023-10-30 18:52 UTC, jMaddrell commented on Firmware/src/config/UIConfig.cpp
> +  prefs.putInt("accentColor", this->getAccentColor());
Given the conversations around fs handling I've left this as nvs for now. Once we have a decision I'm happy to move to JSON

2023-11-01 02:06 UTC, DiverOfDark requested changes

2023-11-01 08:01 UTC, jMaddrell commented on Firmware/src/network/KnomiWebServer.cpp
> +    if (this->config != nullptr && this->config->getUiConfig() != nullptr) {
I got a null response if I loaded the page too quickly, so just added this to guard against it

2023-11-01 08:02 UTC, jMaddrell commented on Firmware/src/config/UIConfig.cpp
> +  prefs.putInt("accentColor", this->getAccentColor());
Let me try changing it back, I was using auto locally and noticed it was using int so changed the type

2023-11-01 08:03 UTC, jMaddrell commented on Firmware/src/network/KnomiWebServer.cpp
> +  pServer->on("/api/themeConfig", HTTP_GET, [&](AsyncWebServerRequest *req) {
Will change

2023-11-01 12:53 UTC, DiverOfDark commented on Firmware/src/network/KnomiWebServer.cpp
> +    if (this->config != nullptr && this->config->getUiConfig() != nullptr) {
OK, let's leave it as is in this PR, but for future we may need to think about API of config system. IMO it's not very practical when we have to check for nullptr before each member access.

2023-11-04 15:20 UTC, jMaddrell commented on Firmware/src/network/KnomiWebServer.cpp
> +  pServer->on("/api/themeConfig", HTTP_GET, [&](AsyncWebServerRequest *req) {
Done

2023-11-04 15:21 UTC, jMaddrell commented on Firmware/src/config/UIConfig.cpp
> +  prefs.putInt("accentColor", this->getAccentColor());
Changed back to uint, it must have been something silly I did when I first made the changes that caused issues.

2023-11-04 15:35 UTC, jMaddrell commented
Added support for theming of background colour as well
![image](https://github.com/DiverOfDark/KNOMI/assets/12979795/55fb6e25-2655-4f3e-b9d8-cc4e45f64ec0)

2023-11-04 21:41 UTC, DiverOfDark approved these changes

2023-11-04 21:41 UTC, merged